version: '3.5'

services:
  vuttr:
    build: .
    container_name: vuttr
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "postgres:5432"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  default:
    external:
      name: backend

volumes:
  vuttr:
