version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - vuttr-network

  api:
    build: .
    container_name: vuttr
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "postgres:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    networks:
      - vuttr-network

volumes:
  pg-data:

networks:
  vuttr-network:
    driver: bridge
